repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.3
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: 1.9.0
    hooks:
    - id: poetry-export
      args: ["-f", "requirements.txt", "-o", "requirements.txt"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        additional_dependencies: [
          'types-requests',
          'types-simplejson',
          'types-PyYAML',
          'sqlalchemy-stubs',
        ]
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: [ --fix ]