services:
  #energy-monitor:
  #  container_name: energy-monitor
  #  image: mholubinka1/octopus-monitoring:latest
  #  labels:
  #    - "com.centurylinklabs.watchtower.enable=true"
  #  volumes:
  #    - /mnt/media/pi-media/monitoring/config/energy-monitor:/config
  #    - /mnt/media/pi-media/monitoring/log/energy-monitor:/log
  #  extra_hosts:
  #    - "host.docker.internal:host-gateway"
  #  restart: unless-stopped
  #  depends_on:
  #    mariadb:
  #      condition: service_healthy
  mariadb:
    container_name: energy-monitor-db
    image: mariadb:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: ${MARIADB_RANDOM_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - /mnt/media/pi-media/monitoring/data/mysql/:/var/lib/mysql/
      - /mnt/media/pi-media/monitoring/config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: "mariadb --user=$${MARIADB_USER} --password=$${MARIADB_PASSWORD} --execute \"SHOW DATABASES;\""
      start_interval: 10s
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped


