services:
  energy-monitor:
    container_name: energy-monitor
    image: mholubinka1/octopus-monitoring:dev
    volumes:
      - /mnt/media/pi-media/monitoring/config/energy-monitor:/config
      - /mnt/media/pi-media/monitoring/log/energy-monitor:/log
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    depends_on:
      - mysql
  mysql:
    container_name: energy-monitor-db
    image: mariadb
    env_file:
      - maria-db/.env
    ports:
      - "3306:3306"
    volumes:
      - /mnt/media/pi-media/monitoring/data/mysql/:/var/lib/mysql/
      - /mnt/media/pi-media/monitoring/config/mysql/:/docker-entrypoint-initdb.d/init.sql
    restart: always
#  influxdb2:
#    container_name: influxdb2
#    image: influxdb:2.7.6
#    ports:
#      - "8082:8082"
#      - "8086:8086"
#      - "8089:8089"
#    volumes:
#      - /mnt/media/pi-media/monitoring/data/influxdb2:/var/lib/influxdb2
#      - /mnt/media/pi-media/monitoring/config/influxdb2:/etc/influxdb2
#    restart: always