version: "3"

services:
  energy-monitor:
    container_name: energy-monitor
    build: ./
    volumes:
      - ./energy-monitor-temp/.config/energy-monitor:/config
      - ./energy-monitor-temp/.log/energy-monitor:/log
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  postgres:
    container_name: energy-db
    build: postgres
    env_file:
      - postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - ./energy-monitor-temp/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U energy-monitor -d octopus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
      