version: "3"

services:
  energy-monitor:
      container_name: energy-monitor
      image: mholubinka1/octopus-monitoring:latest
      volumes:
        - /home/pi/.config/energy-monitor:/config
        - /home/pi/.log/energy-monitor:/log
      extra_hosts:
        - "host.docker.internal:host-gateway"
      restart: unless-stopped