services:
  energy-monitor:
    container_name: energy_monitor
    image: mholubinka1/octopus-monitoring:latest
    volumes:
      - /home/pi/.config/energy-monitor:/config
      - /home/pi/.log/energy-monitor:/log
    restart: unless-stopped