services:  
  maria-db:
    container_name: energy-monitor-db
    image: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      #- /mnt/media/pi-media/monitoring/data/mysql/:/var/lib/mysql/
      - ./enery-monitor-temp:/var/lib/mysql/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    #healthcheck:
    #  test: ["CMD-SHELL", "pg_isready -U energy-monitor -d octopus"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 5
    restart: always