[project]
name = "hive-app"
version = "0.1.0"
description = ""
requires-python = ">=3.13"
dependencies = [
    "requests>=2.34.2",
    "pyyaml>=6.0.3",
    "sqlalchemy>=2.0.52",
    "pymysql>=1.1.2",
    "schedule>=1.2.2",
    "pydantic>=2.13.4",
    "tzdata>=2026.3",
    "pyhive-integration>=1.0.9",
    "common",
]

[tool.uv.sources]
common = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
