services: 
  postgres:
    container_name: energy-db
    build: .
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./energy-monitor-temp/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d octopus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always