name: Code Quality Checks

on:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  checks:
    name: Run all code quality checks
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run code quality checks
        uses: ./.github/actions/code-quality-checks
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
